spring:
  application:
    name: config-profiles
  config:
    import: optional:configserver:http://localhost:8888
  profiles:
    active: dev

#build:
#  id: 1010
#  version: 10.2.3
#  name: "application build"
#  type: "app build"

build:
  id: ${ID}
  version: ${VERSION}
  name: ${NAME}

management:
  endpoints:
    web:
      exposure:
        include: refresh